trigger:
  - master

stages:
- stage: Analyze
  jobs:
  - job: BuildInfo
    displayName: "Buiild Info"
    pool: WorkoutTracker
    workspace:
      clean: all
    timeoutInMinutes: "10"
    steps:
    - script: |
        echo "$(Build.SourceVersion)"
        echo "$(Build.SourceVersionMessage)"
    continueOnError: 'false'
  - job: SonarCloud
    displayName: "SonarCloud"
    pool: WorkoutTracker
    workspace:
      clean: all
    timeoutInMinutes: "10"
    steps:
    - script: |
        sonar-scanner \
        -Dsonar.organization=phobos \
        -Dsonar.projectKey=thefueley_scholar-power-api \
        -Dsonar.sources=. \
        -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: $(SONAR_ENV_TOKEN)
    continueOnError: 'true'
- stage: Build
  jobs:
  - job: DockerBuildPush
    displayName: Docker Build and Push
    pool: WorkoutTracker
    workspace:
      clean: all
    timeoutInMinutes: "10"
    steps:
    - script: |
        make azure
    continueOnError: 'false'