trigger:
  - master

stages:
- stage: Analyze
  jobs:
  - job: SonarCloud
    displayName: "SonarCloud"
    pool: WorkoutTracker
    workspace:
      clean: all
    timeoutInMinutes: "10"
    steps:
    - script: |
        sonar-scanner \
        -Dsonar.organization=phobos \
        -Dsonar.projectKey=thefueley_scholar-power-api \
        -Dsonar.sources=. \
        -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: $(SONAR_ENV_TOKEN)
    continueOnError: 'true'
- stage: Build
  jobs:
  - job: DockerBuildPush
    displayName: Docker Build and Push
    pool: WorkoutTracker
    workspace:
      clean: all
    timeoutInMinutes: "10"
    steps:
    - script: |
        make azure
    continueOnError: 'false'
- stage: Test
  jobs:
  - job: DockerDeploy
    displayName: Push to TEST
    pool: WorkoutTracker
    workspace:
      clean: all
    timeoutInMinutes: "3"
    steps:
    - script: |
        if [ "$(docker ps -aq -f name=test)" ]; then
          docker stop test
          docker rm test
        fi
        docker run -dt --name test -p 3000:3000 --env-file=/home/anax/.scholar.env thefueley/scholar-power-api:1.0
    - task: ado-discord-webhook@1
      condition: failed()
      inputs:
        channelId: $(ADO-CHAN)
        webhookKey: $(DISCORD-WEBHOOK-KEY)
        name: 'ADO'
        messageType: 'embeds'
        embeds: |
          [{
          "title": "Push to TEST Failed",
          "description": "Scholar-Power-API has failed to push to TEST",
          "author": {"name": "Azure DevOps"}
          }]
    continueOnError: 'false'
- stage: Prod
  jobs:
  - job: PushToProd
    pool: WorkoutTracker
    displayName: Push to PROD
    workspace:
      clean: all
    timeoutInMinutes: "3"
    steps:
    - script: |
        echo "Running on host: $(Agent.MachineName)"
        echo "kick off deploy job to PROD"
    - task: ado-discord-webhook@1
      condition: succeeded()
      inputs:
        channelId: $(ADO-CHAN)
        webhookKey: $(DISCORD-WEBHOOK-KEY)
        name: 'ADO'
        messageType: 'embeds'
        embeds: |
          [{
          "title": "ADO Pipeline Complete",
          "description": "All stages have completed successfully",
          "author": {"name": "Azure DevOps"}
          }]
    continueOnError: 'false'