CREATE TABLE IF NOT EXISTS history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT DEFAULT (strftime('%d-%m-%Y', CURRENT_TIMESTAMP)) NOT NULL,
    duration TEXT DEFAULT (strftime('%H-%M-%S', CURRENT_TIMESTAMP)) NOT NULL,
    notes TEXT,
    plan_id INTEGER NOT NULL,
    athlete_id INTEGER NOT NULL,
    FOREIGN KEY (plan_id) REFERENCES workout(plan_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (athlete_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);